#!/bin/bash
# scripts/deploy.sh

set -e

echo "🚀 Deploying Quiz App with Traefik..."

# Check if DNS is configured
echo "🔍 Checking DNS configuration..."
if ! nslookup game.korczewski.de > /dev/null 2>&1; then
    echo "❌ DNS for game.korczewski.de not found. Please configure DNS first."
    exit 1
fi

if ! nslookup auth.korczewski.de > /dev/null 2>&1; then
    echo "❌ DNS for auth.korczewski.de not found. Please configure DNS first."
    exit 1
fi

echo "✅ DNS configuration looks good"

# Create directories and fix permissions
echo "📁 Creating necessary directories..."
mkdir -p letsencrypt
sudo rm -f letsencrypt/acme.json
touch letsencrypt/acme.json
chmod 600 letsencrypt/acme.json

# Stop existing containers
echo "🛑 Stopping existing containers..."
docker-compose down || true

# Clean up old networks
echo "🧹 Cleaning up..."
docker network prune -f || true

# Pull latest images
echo "📦 Pulling latest images..."
docker-compose pull

# Build and start services
echo "🔨 Building and starting services..."
docker-compose up -d --build

# Wait for services to be ready
echo "⏳ Waiting for services to start..."
sleep 45

# Check health
echo "🏥 Checking service health..."
docker-compose ps

echo "✅ Deployment complete!"
echo ""
echo "🌐 Your application should be available at:"
echo "   Auth: https://auth.korczewski.de"
echo "   Game: https://game.korczewski.de"
echo "   Traefik Dashboard: http://$(curl -s ifconfig.me):8080"
echo ""
echo "📝 To check logs:"
echo "   docker-compose logs -f"
echo ""
echo "🔐 SSL certificates will be automatically generated by Let's Encrypt"
echo "   This may take 2-3 minutes on first run"